Update Methods.md
mattias-p/zonemaster pull request #2
Opened 2018-03-02 09:38 UTC by matsduf

2018-03-02 11:48 UTC, mattias-p requested changes
This is getting detailed. And long.

Have you considered adding a section for inputs? That way inputs could be referenced by name instead of explanation. Second, assumptions about the inputs could be moved from the algorithm section and into the inputs section. Third, I think it makes sense to list the caches that are being used here.

Have you considered also adding a section for state? That way the methods that update caches can declare up front which ones, and the ones that don't can declare that they're stateless.

Have you considered adding a section for return values? That way methods can declare up front whether they can fail or not. Second, descriptions of the meaning of the return value could be moved from the algorithm section and into the return values section. Third, steps that just declare success could be removed as that would be implicit from the fact that the method returns a value.

2018-03-02 11:48 UTC, mattias-p commented on docs/specifications/tests/Methods.md
> +3. Ignore any name servers provided by delegation from parent zone.
Steps B.2 and B.3 are noops, right? Have you considered moving them to the description?

2018-03-02 11:48 UTC, mattias-p commented on docs/specifications/tests/Methods.md
> +3. If no child zone exists, method fails.
Have you considered combining steps A.2 and A.3 into a single condition?

2018-03-02 11:48 UTC, mattias-p commented on docs/specifications/tests/Methods.md
> +   3.1 The method succeeds.
Have you considered using proper lists? That would increase the spacing between the numbering and the content, making it easier on the eye.

2018-03-02 11:48 UTC, mattias-p commented on docs/specifications/tests/Methods.md
> +   is kept. The cache overwrites the cache from method 1 and is to be used by method 4.
Is the caching stuff related to the previous step?

2018-03-02 11:48 UTC, mattias-p commented on docs/specifications/tests/Methods.md
>  3. Collect all IPv4 and IPv6 addresses in the input to the undelegated test and
The numbering is off now.

2018-05-17 11:09 UTC, matsduf commented
Not relevant anymore.

2018-05-17 11:09 UTC, closed without merging